version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: easyupdate
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - db

  client:
    build:
      context: .
      dockerfile: apps/client/Dockerfile
    ports:
      - "3000:80"

volumes:
  pgdata:
